# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20180326_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(),
        ),
    ]
