# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='desc',
            new_name='email',
        ),
    ]
